server:
  port: 8000

spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-1.cw2m6xryal2i.ap-northeast-2.rds.amazonaws.com:3306/back-20220829
    username: junil
    password: 1q2w3e4r
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/junil/junil/web/springboot/springboot-mybatis-20220923-junil/upload/